pjmedia_transport_attach_param Struct Reference (2.13)
Home --> Documentations --> PJMEDIA Reference
pjmedia_transport_attach_param Struct Reference
Media Transport
#include <transport.h>
Data Fields
void * stream
pjmedia_type media_type
pj_sockaddr rem_addr
pj_sockaddr rem_rtcp
unsigned addr_len
void * user_data
void(* rtp_cb)(void *user_data, void *pkt, pj_ssize_t)
void(* rtcp_cb)(void *user_data, void *pkt, pj_ssize_t)
void(* rtp_cb2)(pjmedia_tp_cb_param *param)
Detailed Description
This structure describes the data passed when calling pjmedia_transport_attach2().
Forward declaration for media transport attach param.
Field Documentation
stream
void* pjmedia_transport_attach_param::stream
The media stream.
media_type
pjmedia_type pjmedia_transport_attach_param::media_type
Indicate the stream type, either it's audio (PJMEDIA_TYPE_AUDIO) or video (PJMEDIA_TYPE_VIDEO).
rem_addr
pj_sockaddr pjmedia_transport_attach_param::rem_addr
Remote RTP address to send RTP packet to.
Referenced by pjmedia_transport_attach(), and pjmedia_transport_attach2().
rem_rtcp
pj_sockaddr pjmedia_transport_attach_param::rem_rtcp
Optional remote RTCP address. If the argument is NULL or if the address is zero, the RTCP address will be calculated from the RTP address (which is RTP port plus one).
Referenced by pjmedia_transport_attach(), and pjmedia_transport_attach2().
addr_len
unsigned pjmedia_transport_attach_param::addr_len
Length of the remote address.
Referenced by pjmedia_transport_attach(), and pjmedia_transport_attach2().
user_data
void* pjmedia_transport_attach_param::user_data
Arbitrary user data to be set when the callbacks are called.
Referenced by pjmedia_transport_attach(), and pjmedia_transport_attach2().
rtp_cb
void(* pjmedia_transport_attach_param::rtp_cb) (void *user_data, void *pkt, pj_ssize_t)
Callback to be called when RTP packet is received on the transport.
Referenced by pjmedia_transport_attach(), and pjmedia_transport_attach2().
rtcp_cb
void(* pjmedia_transport_attach_param::rtcp_cb) (void *user_data, void *pkt, pj_ssize_t)
Callback to be called when RTCP packet is received on the transport.
Referenced by pjmedia_transport_attach(), and pjmedia_transport_attach2().
rtp_cb2
void(* pjmedia_transport_attach_param::rtp_cb2) (pjmedia_tp_cb_param *param)
Callback to be called when RTP packet is received on the transport.
The documentation for this struct was generated from the following file:
transport.h
PJMEDIA small footprint Open Source media stack
Copyright (C) 2006-2008 Teluu Inc.